on:
  push:
    branches:
      - main
name: Handle Windows Release
jobs:
  generate:
    name: Create release-artifacts
    runs-on: ubuntu-latest
    defaults:
        run:
            working-directory: ./Bot
    steps:
      - name: PyInstaller Windows
        uses: JackMcKew/pyinstaller-action-windows@main
        with:
          path: .

      - uses: actions/upload-artifact@v2
        with:
          name: name-of-artifact
          path: ./dist/windows
